### ISSUE TITLE
My Code is ready

### ISSUE THREAD

**Issue by maheshdeshmukh1982** [maheshdeshmukh1982/sampalejava#1]
Pls test my code

**Comment by manojgawankar** [comment]
starting build process

**Comment by manojgawankar** [comment]
Build Successful

**Comment by manojgawankar** [comment]
Testing Started

**Comment by manojgawankar** [comment]
Te

**Comment by manojgawankar** [comment]
Testing Failed  Please review the report @xyz.com

**Comment by manojgawankar** [comment]
Build server is getting prepared.

**Comment by manojgawankar** [comment]
Build Server is Ready

**Comment by manojgawankar** [comment]
@harsh-ghl Please build the application

**Comment by harsh-ghl** [comment]
Build is successful

**Comment by harsh-ghl** [comment]
@manojgawankar Please prepare test server

**Comment by manojgawankar** [comment]
Preparing Test Server

**Comment by manojgawankar** [comment]
Preparing OS

**Comment by manojgawankar** [comment]
preparing DB configuration ready

**Comment by manojgawankar** [comment]
@harsh-ghl Please Deploy the Application

**Comment by harsh-ghl** [comment]
Deployment successful

**Comment by harsh-ghl** [comment]
Starting testing

**Comment by harsh-ghl** [comment]
Testing Failed review the reports at xyz.com

**Comment by maheshdeshmukh1982** [comment]
Reviewed the report fixing the bugs

**Comment by maheshdeshmukh1982** [comment]
Reviewed the report fixing the bugs
